### ISSUE TITLE
Escaping editing fields loses work by default

### ISSUE THREAD

**Issue by jackfischer** [edgedb/edgedb-ui#324] opened 2024-02-19 21:58 UTC
When editing fields you have to specifically click the green right facing arrow to save the field. Clicking anywhere else discards your work with no warning. 
It is by _far_ more common to intend to save a field after editing it, and very rare to intentionally discard your work. However, the UI heavily biases towards discarding - clicking anywhere else on the UI, including adjacent fields to keep editing (very common) discards your edits. Despite being experienced with the UI I still routinely make this mistake, which leads me to believe there is something fundamentally "off" about the current implementation.

**Comment by jaclarke** [comment] 2024-02-22 22:24
Duplicate of #310

**Closed by jaclarke** 2024-02-22 22:24 UTC
