### ISSUE TITLE
Show the field of link property in the data table.

### ISSUE THREAD

**Issue by AnsonHwang86** [edgedb/edgedb-ui#312] opened 2024-02-03 06:30 UTC
![image](https://github.com/edgedb/edgedb-ui/assets/16233397/514a1cf6-a302-45ac-ab04-0af48f3867ea)
Above is my data, 
but I can't found Any link property I define in schema(such as @relationship, @qty, @instruction).

Here is my schema.
```
type Bom  {
		title: str;
		multi components: Component {relationship: str; qty: float32; instruction: str;};
		multi notes: str;
	}

type Component {
        name:  str;
        sku: str;
       ...
    }
```

**Comment by raddevon** [comment] 2024-02-05 14:06
Duplicate of #11

**Closed by raddevon** 2024-02-05 14:06 UTC
